FROM aerospike:latest
RUN echo ========AEROSPIKE_INSTALLING================================================
MAINTAINER Luciano Jr <luciano@lucianojr.com.br>

RUN rm /etc/aerospike/aerospike.conf

ADD aerospike.conf /etc/aerospike/aerospike.conf